# config.yaml
paths:
  train_path: '../data/train.csv'
  train_aug_path: '../data/processed_train.csv'
  dev_path: '../data/processed_dev.csv'
  test_path: '../data/processed_dev.csv'
  predict_path: '../data/test.csv'
  model_path: './model/kykim_electra-kor-base_L1_lr1e-5_b16_e30_rmsprop.pt'  #pt파일로 저장될 모델의 경로와 파일 이름
  output_path: '../data/output/'

model_params: dd
  model_name: 'kykim/electra-kor-base'
  batch_size: 16
  max_epoch: 30
  shuffle: True
  learning_rate: 1e-5
  
wandb_params:
  project: 'heonhyo'
  entity: 'junior-naver'
  allow_val_change: True
  dataset: 'default data'
  run_name: 'kykim_electra-kor-base_L1_lr1e-5_b16_e30_rmsprop' #wandb에 표시될 모델 버전의 이름
