# config.yaml
paths:
  train_path: '../data/train.csv'
  train_process_path: '../data/train.csv'
  dev_process_path: '../data/dev.csv'
  train_aug_path: '../data/neda_train_trans_thirty.csv'
  dev_path: '../data/npart_processed_dev.csv'
  test_path: '../data/npart_processed_dev.csv'
  predict_path: '../data/test.csv'
  model_path: './model/neda_thirty_kykim_electra-kor-base_nadam_mse_lr1e-5_b16_e20.pt'  #pt파일로 저장될 모델의 경로와 파일 이름
  output_path: '../data/output/'

model_params: 
  model_name: 'kykim/electra-kor-base'
  batch_size: 16
  max_epoch: 20
  shuffle: True
  learning_rate: 1e-5
  
wandb_params:
  project: 'dayeon_1'
  entity: 'junior-naver'
  allow_val_change: True
  dataset: 'default data'
  run_name: 'neda_thirty_kykim_electra-kor-base_nadam_mse_lr1e-5_b16_e20' #wandb에 표시될 모델 버전의 이름
