# config.yaml
paths:
  train_path: '../data/train.csv'
  train_aug_path: '../data/processed_train.csv'
  dev_path: '../data/dev.csv'
  dev_aug_path: '../data/processed_dev.csv'
  test_aug_path: '../data/dev.csv'
  test_path: '../data/processed_dev.csv'
  predict_path: '../data/test.csv'
  model_path: './model/daekeun-ml-koelectra-small-v3-korsts-ver1.pt'  #pt파일로 저장될 모델의 경로와 파일 이름
  output_path: '../data/output/'

model_params: 
  model_name: 'daekeun-ml/koelectra-small-v3-korsts'
  batch_size: 32
  max_epoch: 30
  shuffle: True
  learning_rate: 1e-5
  
wandb_params:
  project: 'sujeong_project'
  entity: 'junior-naver'
  allow_val_change: True
  dataset: 'default data'
  run_name: 'daekeun-ml-koelectra-small-v3-korsts-ver1' #wandb에 표시될 모델 버전의 이름
  loss: 'MSE'
  optimizer : 'NAdam'