# config.yaml
paths:
  train_path: '../data/train.csv'
  train_process_path: '../data/train_translated.csv'
  dev_process_path: '../data/dev.csv'
  train_aug_path: '../data/eda_train_trans_fifteen.csv'
  dev_path: '../data/part_processed_dev.csv'
  test_path: '../data/part_processed_dev.csv'
  predict_path: '../data/test.csv'
  model_path: './model/snunlp-KR-SBERT-V40K-klueNLI-augSTS-eda-15.pt'  #pt파일로 저장될 모델의 경로와 파일 이름
  output_path: '../data/output/'

model_params: 
  model_name: 'snunlp/KR-SBERT-V40K-klueNLI-augSTS'
  batch_size: 16
  max_epoch: 20
  shuffle: True
  learning_rate: 1e-5
  
wandb_params:
  project: 'sujeong_project'
  entity: 'junior-naver'
  allow_val_change: True
  dataset: 'default data'
  run_name: 'snunlp-KR-SBERT-V40K-klueNLI-augSTS-eda-15' #wandb에 표시될 모델 버전의 이름
  loss: 'MSE'
  optimizer : 'NAdam'