# config.yaml
paths:
  train_path: '../data/train.csv'
  train_aug_path: '../data/train_aug.csv'
  dev_path: '../data/dev.csv'
  test_path: '../data/dev.csv'
  predict_path: '../data/test.csv'
  model_path: './model/KcELECTRA-base_L1_lr1e-5_b16_e30.pt'  #pt파일로 저장될 모델의 경로와 파일 이름
  output_path: '../data/output/KcELECTRA-base_L1_lr1e-5_b16_e30'

model_params: 
  model_name: 'beomi/KcELECTRA-base'
  batch_size: 16
  max_epoch: 30
  shuffle: True
  learning_rate: 1e-5
  
wandb_params:
  project: 'dayeon_1'
  entity: 'junior-naver'
  allow_val_change: True
  dataset: 'default data'
  run_name: 'KcELECTRA-base_L1_lr1e-5_b16_e30' #wandb에 표시될 모델 버전의 이름
