# config.yaml
paths:
  train_path: '../data/train.csv'
  dev_path: '../data/dev.csv'
  test_path: '../data/dev.csv'
  predict_path: '../data/test.csv'
  model_path: './model/model_naver_epoch50_3.pt'  #pt파일로 저장될 모델의 경로와 파일 이름
  output_path: '../data/output/'

model_params: 
  model_name: 'klue/roberta-small'
  batch_size: 16
  max_epoch: 50
  shuffle: True
  learning_rate: 1e-5
  amsgrad: False
  
wandb_params:
  project: 'heonhyo'
  entity: 'junior-naver'
  allow_val_change: True
  dataset: 'default data'
  run_name: 'naver-epoch50_3' #wandb에 표시될 모델 버전의 이름